export const EVENTOS = [
  {
    id: 1,
    nombre: 'Summit Tech Ibagué 2026',
    organizador: 'TechHub Tolima',
    fecha: '15 Jun 2026',
    lugar: 'Ibagué, Tolima',
    categoria: 'Conferencia',
    precio: '$45.000',
    badge: 'destacado',
    modalidad: 'Presencial',
    estado: 'proximo',
  },
  {
    id: 2,
    nombre: 'Taller de Diseño UX/UI para principiantes',
    organizador: 'Unibagué Labs',
    fecha: '20 Jun 2026',
    lugar: 'Virtual',
    categoria: 'Taller',
    precio: 'Gratis',
    badge: 'gratuito',
    modalidad: 'Virtual',
    estado: 'proximo',
  },
  {
    id: 3,
    nombre: 'Networking Empresarial — Tolima 2026',
    organizador: 'Cámara de Comercio',
    fecha: '22 Jun 2026',
    lugar: 'Ibagué, Tolima',
    categoria: 'Networking',
    precio: '$20.000',
    badge: 'ultimos',
    modalidad: 'Presencial',
    estado: 'proximo',
  },
  {
    id: 4,
    nombre: 'Festival de Música Folclórica del Tolima',
    organizador: 'Alcaldía de Ibagué',
    fecha: '1 Jul 2026',
    lugar: 'Parque Centenario',
    categoria: 'Concierto',
    precio: 'Gratis',
    badge: 'gratuito',
    modalidad: 'Presencial',
    estado: 'proximo',
  },
  {
    id: 5,
    nombre: 'Maratón Internacional Ciudad Musical',
    organizador: 'Liga Atlética Tolima',
    fecha: '28 May 2026',
    lugar: 'Ibagué, Tolima',
    categoria: 'Deporte',
    precio: '$80.000',
    badge: 'soldout',
    modalidad: 'Presencial',
    estado: 'finalizado',
  },
  {
    id: 6,
    nombre: 'Congreso Nacional de Inteligencia Artificial',
    organizador: 'ACIS Colombia',
    fecha: '10 Jul 2026',
    lugar: 'Híbrido',
    categoria: 'Conferencia',
    precio: '$120.000',
    badge: null,
    modalidad: 'Híbrido',
    estado: 'proximo',
  },
  {
    id: 7,
    nombre: 'Workshop: Clean Architecture en Node.js',
    organizador: 'DevCommunity CO',
    fecha: '18 Jun 2026',
    lugar: 'Virtual',
    categoria: 'Taller',
    precio: '$35.000',
    badge: null,
    modalidad: 'Virtual',
    estado: 'proximo',
  },
  {
    id: 8,
    nombre: 'Feria Empresarial Tolima Innova',
    organizador: 'Gobernación del Tolima',
    fecha: '5 Jul 2026',
    lugar: 'Ibagué, Tolima',
    categoria: 'Networking',
    precio: 'Gratis',
    badge: 'gratuito',
    modalidad: 'Presencial',
    estado: 'proximo',
  },
  {
    id: 9,
    nombre: 'Hackathon Social Impact 2026',
    organizador: 'Universidad de Ibagué',
    fecha: '12 Jul 2026',
    lugar: 'Ibagué, Tolima',
    categoria: 'Taller',
    precio: 'Gratis',
    badge: 'gratuito',
    modalidad: 'Presencial',
    estado: 'proximo',
  },
]
